[platformio]
src_dir = src

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_extra_dirs = C:/Users/info/Documents/Arduino/libraries
lib_ldf_mode = deep+
build_flags =
    -I.
    -D SERIAL_RX_BUFFER_SIZE=128
